# Unit tests for agent-iam — the IAM substrate the eks-agent-platform operator runs
# on. This component mints the operator's own role plus the tenant permissions
# boundary that caps every tenant role, so its security contract is the crown-jewel
# invariant of the whole platform: the operator must never be able to create an
# unbounded role, and the boundary must deny the privilege-escalation verbs.
#
# Runs at `command = plan` against a mocked AWS provider (no account, no network).
# aws_caller_identity / aws_partition are mocked so the account-qualified ARNs
# resolve; every policy under test is built with jsonencode() directly in config,
# so its content is real and known at plan time — only synthetic .arn/.id values
# are generated by the mock, which is exactly what the cross-resource boundary
# reference needs.

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:user/test"
      user_id    = "AIDTEST"
    }
  }
  mock_data "aws_partition" {
    defaults = {
      partition          = "aws"
      dns_suffix         = "amazonaws.com"
      reverse_dns_prefix = "com.amazonaws"
    }
  }
}

# The operator trust is rendered by aws_iam_policy_document, which the mock turns
# into a non-JSON placeholder and the aws_iam_role policy validator then rejects.
# We don't assert on the operator's OIDC trust here (its shape isn't the escalation
# surface these tests guard — the boundary gate is), so feed a valid JSON stub so
# the role plans and the boundary/write-gate assertions can run.
override_data {
  target = data.aws_iam_policy_document.operator_trust
  values = {
    json = "{\"Version\":\"2012-10-17\",\"Statement\":[]}"
  }
}

variables {
  environment       = "dev"
  region            = "us-west-2"
  oidc_provider_arn = "arn:aws:iam::123456789012:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/EXAMPLED"
  oidc_issuer       = "oidc.eks.us-west-2.amazonaws.com/id/EXAMPLED"
}

# The load-bearing invariant: the operator can create/modify a tenant role ONLY
# when that role carries the tenant permissions boundary. Drop the condition and
# the operator becomes an unbounded role factory — straight-line privilege
# escalation. Asserted structurally (find the statement by Sid) so statement
# ordering can't hide a regression.
run "operator_tenant_write_is_boundary_gated" {
  command = plan

  assert {
    condition = length([
      for s in jsondecode(aws_iam_role_policy.operator.policy).Statement :
      s if try(s.Sid, "") == "TenantRoleWriteWithBoundary"
      && try(s.Condition.StringEquals["iam:PermissionsBoundary"], "") == aws_iam_policy.tenant_boundary.arn
    ]) == 1
    error_message = "operator tenant-role CreateRole/*RolePolicy must be gated by iam:PermissionsBoundary == the tenant boundary; an ungated write is a privilege-escalation path"
  }

  # ...and the write is scoped to the tenant path, never Resource="*".
  assert {
    condition = alltrue([
      for s in jsondecode(aws_iam_role_policy.operator.policy).Statement :
      try(s.Resource, "") == "arn:aws:iam::123456789012:role/eks-agent-platform/tenants/*"
      if try(s.Sid, "") == "TenantRoleWriteWithBoundary"
    ])
    error_message = "tenant-role write must be scoped to the /eks-agent-platform/tenants/ path ARN, not a wildcard"
  }
}

# The per-Platform session role the operator mints for humans is gated the same
# way — it must never be able to create a role that outranks the boundary.
run "operator_session_role_write_is_boundary_gated" {
  command = plan

  assert {
    condition = length([
      for s in jsondecode(aws_iam_role_policy.operator.policy).Statement :
      s if try(s.Sid, "") == "PlatformSessionRoleWriteWithBoundary"
      && try(s.Condition.StringEquals["iam:PermissionsBoundary"], "") == aws_iam_policy.tenant_boundary.arn
    ]) == 1
    error_message = "operator session-role write must also be gated by the tenant permissions boundary"
  }
}

# PassRole for the tenant role is constrained to the EKS Pod Identity service —
# an unconstrained PassRole lets the operator hand the tenant role to anything.
run "operator_passrole_is_service_constrained" {
  command = plan

  assert {
    condition = length([
      for s in jsondecode(aws_iam_role_policy.operator.policy).Statement :
      s if try(s.Sid, "") == "PassTenantRoleToPodIdentity"
      && try(s.Condition.StringEquals["iam:PassedToService"], "") == "pods.eks.amazonaws.com"
    ]) == 1
    error_message = "PassRole on the tenant role must be constrained to pods.eks.amazonaws.com"
  }
}

# The tenant permissions boundary is the ceiling. It must Deny the three
# escalation verbs (org/account settings + AssumeRole) outright — a tenant role
# can never re-org the account or jump to another role, no matter what policy is
# attached under the boundary.
run "boundary_denies_escalation" {
  command = plan

  assert {
    condition = length([
      for s in jsondecode(aws_iam_policy.tenant_boundary.policy).Statement :
      s if try(s.Sid, "") == "DenyEscalation" && s.Effect == "Deny"
      && contains(s.Action, "organizations:*")
      && contains(s.Action, "account:*")
      && contains(s.Action, "sts:AssumeRole")
    ]) == 1
    error_message = "tenant boundary must Deny organizations:*, account:*, and sts:AssumeRole (the escalation verbs)"
  }

  # IAM is denied wholesale except on scheduler-invoke roles (NotResource), so a
  # tenant role can never mint, modify, or read identities.
  assert {
    condition = length([
      for s in jsondecode(aws_iam_policy.tenant_boundary.policy).Statement :
      s if try(s.Sid, "") == "DenyIamOutsideSchedulerInvokePass" && s.Effect == "Deny"
      && contains(s.Action, "iam:*")
      && try(s.NotResource, "") == "arn:aws:iam::123456789012:role/*-scheduler-invoke"
    ]) == 1
    error_message = "tenant boundary must Deny iam:* everywhere except NotResource the scheduler-invoke roles"
  }

  # The only IAM the boundary permits is PassRole to the Scheduler service.
  assert {
    condition = length([
      for s in jsondecode(aws_iam_policy.tenant_boundary.policy).Statement :
      s if try(s.Sid, "") == "SchedulerInvokeRolePass" && s.Effect == "Allow"
      && s.Action == ["iam:PassRole"]
      && try(s.Condition.StringEquals["iam:PassedToService"], "") == "scheduler.amazonaws.com"
    ]) == 1
    error_message = "the boundary's only IAM Allow must be PassRole constrained to scheduler.amazonaws.com"
  }
}

# The operator role itself lives under the platform path (its own writes are
# boundary-gated by whatever mints it), and the read grant is scoped to tenant
# role ARNs, never "*".
run "operator_role_shape" {
  command = plan

  assert {
    condition     = aws_iam_role.operator.path == "/eks-agent-platform/"
    error_message = "operator role must live under /eks-agent-platform/"
  }

  assert {
    condition = alltrue([
      for s in jsondecode(aws_iam_role_policy.operator.policy).Statement :
      !contains(try(tolist(s.Resource), []), "*")
      if try(s.Sid, "") == "TenantRoleRead"
    ])
    error_message = "operator tenant-role read must be scoped to tenant ARNs, never Resource=\"*\""
  }
}

# The artifact + eval buckets hold model weights and evaluation evidence. Public
# access is blocked at the bucket (the operator writes a bucket policy at runtime,
# so a mistaken policy must not be able to expose them) and versioning is on so an
# overwrite can't destroy prior evidence.
run "artifact_buckets_are_locked_down" {
  command = plan

  assert {
    condition = alltrue([
      aws_s3_bucket_public_access_block.model_artifacts.block_public_acls,
      aws_s3_bucket_public_access_block.model_artifacts.block_public_policy,
      aws_s3_bucket_public_access_block.model_artifacts.ignore_public_acls,
      aws_s3_bucket_public_access_block.model_artifacts.restrict_public_buckets,
      aws_s3_bucket_public_access_block.eval_reports.block_public_acls,
      aws_s3_bucket_public_access_block.eval_reports.block_public_policy,
      aws_s3_bucket_public_access_block.eval_reports.ignore_public_acls,
      aws_s3_bucket_public_access_block.eval_reports.restrict_public_buckets,
    ])
    error_message = "model-artifacts and eval-reports buckets must block all public access"
  }

  assert {
    condition = (
      aws_s3_bucket_versioning.model_artifacts.versioning_configuration[0].status == "Enabled" &&
      aws_s3_bucket_versioning.eval_reports.versioning_configuration[0].status == "Enabled"
    )
    error_message = "artifact + eval-report buckets must have versioning Enabled (evidence must survive overwrite)"
  }
}

# The tenant baseline is the real Bedrock GRANT attached to every tenant role (the
# permissions boundary above is only the ceiling). It must scope model invocation
# to the allowlisted foundation-model ARNs + their inference profiles — never
# Resource="*" — and it must NOT smuggle the guardrail action onto that
# model-scoped resource (guardrails are a different resource type).
run "tenant_baseline_bedrock_is_model_scoped" {
  command = plan

  # BedrockInvoke: Resource is the expanded allowlist (a list carrying the
  # anthropic.* foundation-model ARN), and the "*" wildcard is absent. can(tolist)
  # also fails the assertion if Resource regresses to the bare "*" string.
  assert {
    condition = length([
      for s in jsondecode(aws_iam_policy.tenant_baseline.policy).Statement :
      s if try(s.Sid, "") == "BedrockInvoke"
      && can(tolist(s.Resource))
      && contains(tolist(s.Resource), "arn:aws:bedrock:*::foundation-model/anthropic.*")
      && contains(tolist(s.Resource), "arn:aws:bedrock:*:123456789012:inference-profile/*anthropic.*")
      && !contains(tolist(s.Resource), "*")
    ]) == 1
    error_message = "BedrockInvoke must scope Resource to the allowlisted foundation-model + inference-profile ARNs (incl. anthropic.*), never \"*\""
  }

  # The invoke/converse actions stay on the scoped statement...
  assert {
    condition = alltrue([
      for s in jsondecode(aws_iam_policy.tenant_baseline.policy).Statement :
      contains(s.Action, "bedrock:InvokeModel") && contains(s.Action, "bedrock:Converse")
      if try(s.Sid, "") == "BedrockInvoke"
    ])
    error_message = "BedrockInvoke must still carry the invoke + converse actions"
  }

  # ...but ApplyGuardrail must NOT ride on the model-scoped invoke statement.
  assert {
    condition = alltrue([
      for s in jsondecode(aws_iam_policy.tenant_baseline.policy).Statement :
      !contains(s.Action, "bedrock:ApplyGuardrail")
      if try(s.Sid, "") == "BedrockInvoke"
    ])
    error_message = "ApplyGuardrail must not ride on the model-scoped BedrockInvoke statement"
  }

  # Guardrail is its own statement, scoped to in-account guardrail ARNs, not "*".
  assert {
    condition = length([
      for s in jsondecode(aws_iam_policy.tenant_baseline.policy).Statement :
      s if try(s.Sid, "") == "BedrockGuardrail"
      && contains(s.Action, "bedrock:ApplyGuardrail")
      && try(s.Resource, "") == "arn:aws:bedrock:*:123456789012:guardrail/*"
    ]) == 1
    error_message = "ApplyGuardrail must be its own statement scoped to guardrail/* in-account"
  }
}

# The scoping is variable-driven, not hardcoded: an empty allowlist is the
# documented escape hatch back to Resource=["*"]. Proving both directions rules out
# a coincidentally-correct default.
run "tenant_baseline_bedrock_empty_allowlist_is_wildcard" {
  command = plan

  variables {
    bedrock_allowed_model_ids = []
  }

  assert {
    condition = length([
      for s in jsondecode(aws_iam_policy.tenant_baseline.policy).Statement :
      s if try(s.Sid, "") == "BedrockInvoke"
      && length(tolist(s.Resource)) == 1 && contains(tolist(s.Resource), "*")
    ]) == 1
    error_message = "an empty allowlist must fall back to exactly one BedrockInvoke statement with Resource=[\"*\"] (the explicit escape hatch)"
  }
}
