# Unit tests for org-security — the org-wide detection & alerting plane. This
# component turns on the two guardrails every account leans on (GuardDuty threat
# detection, Security Hub compliance standards) and wires their findings to a
# shared SNS alert topic. Its security contract is therefore: the guardrails are
# actually ENABLED (not just declared-then-disabled), the RIGHT compliance
# standards are subscribed, the alert channel only accepts publishes from the
# three AWS services that own it (never a wildcard principal that would let any
# account inject spoofed "all-clear" alerts), and the finding routers actually
# match the high/critical findings they exist to escalate.
#
# Runs at `command = plan` against a mocked AWS provider (no account, no network).
# aws_caller_identity / aws_region are mocked so the account/region resolve; every
# policy and event-pattern under assertion is built with jsonencode() inline, so
# its content is REAL and known at plan time — only the synthetic SNS topic .arn
# is generated by the mock, which is exactly what the Resource cross-reference
# needs. There is no aws_iam_policy_document in this component, so nothing is
# mangled by the mock — this is the clean, high-confidence assertion path.

mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:user/test"
      user_id    = "AIDTEST"
    }
  }
  mock_data "aws_region" {
    defaults = {
      name = "us-west-2"
    }
  }
  # The SNS topic .arn is consumed as a real ARN by the topic policy and the
  # EventBridge targets, which the provider ARN-validates at plan. Give the mock a
  # syntactically valid ARN so those resources plan; this same value is what the
  # policy's Resource is compared against, so the scoping assertion stays real.
  mock_resource "aws_sns_topic" {
    defaults = {
      arn = "arn:aws:sns:us-west-2:123456789012:org-security-alerts"
    }
  }
}

variables {
  environment = "development"
  region      = "us-west-2"
  team        = "platform"
}

# INVARIANT 1 — the shared security-alerts topic accepts sns:Publish ONLY from the
# three named AWS service principals. This is the load-bearing boundary: a wildcard
# principal (Principal="*") or a widened Action (sns:*) would let any account inject
# forged security findings into the alert channel operators trust, or drain/alter it.
# Asserted structurally (find each grant by Sid) so statement reordering can't hide a
# regression, plus a whole-policy sweep that no statement escapes the scoping.
run "sns_publish_scoped_to_named_services" {
  command = plan

  assert {
    condition = length([
      for s in jsondecode(aws_sns_topic_policy.security_alerts.policy).Statement :
      s if try(s.Sid, "") == "AllowGuardDutyPublish"
      && s.Effect == "Allow"
      && try(s.Principal.Service, "") == "guardduty.amazonaws.com"
      && s.Action == "sns:Publish"
      && s.Resource == aws_sns_topic.security_alerts.arn
    ]) == 1
    error_message = "GuardDuty publish grant must be Allow sns:Publish, Principal Service=guardduty.amazonaws.com, scoped to the alerts topic"
  }

  assert {
    condition = length([
      for s in jsondecode(aws_sns_topic_policy.security_alerts.policy).Statement :
      s if try(s.Sid, "") == "AllowSecurityHubPublish"
      && s.Effect == "Allow"
      && try(s.Principal.Service, "") == "securityhub.amazonaws.com"
      && s.Action == "sns:Publish"
    ]) == 1
    error_message = "Security Hub publish grant must be Allow sns:Publish, Principal Service=securityhub.amazonaws.com"
  }

  assert {
    condition = length([
      for s in jsondecode(aws_sns_topic_policy.security_alerts.policy).Statement :
      s if try(s.Sid, "") == "AllowEventBridgePublish"
      && s.Effect == "Allow"
      && try(s.Principal.Service, "") == "events.amazonaws.com"
      && s.Action == "sns:Publish"
    ]) == 1
    error_message = "EventBridge publish grant must be Allow sns:Publish, Principal Service=events.amazonaws.com"
  }

  # Whole-policy sweep: EVERY statement must publish only (Action=sns:Publish, never
  # sns:* / *) from a KNOWN service principal (try(...) falls back to "*" if Principal
  # was widened to the "*" string, which then fails the allow-list check), scoped to
  # the topic ARN. This is what catches a wildcard-principal or widened-action mutation.
  assert {
    condition = alltrue([
      for s in jsondecode(aws_sns_topic_policy.security_alerts.policy).Statement :
      s.Action == "sns:Publish"
      && contains(["events.amazonaws.com", "guardduty.amazonaws.com", "securityhub.amazonaws.com"], try(s.Principal.Service, "*"))
      && s.Resource == aws_sns_topic.security_alerts.arn
    ])
    error_message = "every alerts-topic statement must be sns:Publish from a named service principal scoped to the topic — no wildcard principal, no widened action"
  }
}

# INVARIANT 2 — GuardDuty is actually turned ON. The detector's enable=true is the
# master threat-detection switch; if it silently flips to false the resource still
# exists (looks configured) but detects nothing. The detection datasources (S3
# access analysis, EKS audit-log monitoring, EBS malware scanning) are the surfaces
# the platform relies on, defaulted on — assert they flow through enabled.
run "guardduty_detector_enabled" {
  command = plan

  assert {
    condition     = aws_guardduty_detector.this[0].enable == true
    error_message = "GuardDuty detector must be enabled (enable=true) — the master threat-detection switch"
  }

  assert {
    condition = (
      aws_guardduty_detector.this[0].datasources[0].s3_logs[0].enable == true &&
      aws_guardduty_detector.this[0].datasources[0].kubernetes[0].audit_logs[0].enable == true &&
      aws_guardduty_detector.this[0].datasources[0].malware_protection[0].scan_ec2_instance_with_findings[0].ebs_volumes[0].enable == true
    )
    error_message = "GuardDuty S3, EKS audit-log, and EBS malware detection datasources must be enabled by default"
  }
}

# INVARIANT 3 — Security Hub is enabled and the EXPECTED compliance standards are
# subscribed. enable_default_standards=false means standards are managed explicitly,
# so if the subscription for_each breaks (or the default standards list is emptied)
# no benchmark runs and compliance drift goes unseen. Assert the two crown-jewel
# standards (CIS AWS Foundations v3.0.0, AWS Foundational Security Best Practices)
# are present, keyed by ARN, and that each subscription's ARN matches its key.
run "securityhub_enabled_with_expected_standards" {
  command = plan

  assert {
    condition     = length(aws_securityhub_account.this) == 1
    error_message = "Security Hub account must be enabled"
  }

  assert {
    condition = (
      contains(keys(aws_securityhub_standards_subscription.this), "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/3.0.0") &&
      contains(keys(aws_securityhub_standards_subscription.this), "arn:aws:securityhub:::standards/aws-foundational-security-best-practices/v/1.0.0")
    )
    error_message = "Security Hub must subscribe CIS AWS Foundations v3.0.0 and AWS Foundational Security Best Practices standards"
  }

  assert {
    condition = alltrue([
      for k, sub in aws_securityhub_standards_subscription.this : sub.standards_arn == k
    ])
    error_message = "each standards subscription's standards_arn must equal its ARN key (no cross-wiring)"
  }
}

# INVARIANT 4 — the finding routers actually match the findings they escalate. The
# EventBridge rules are the only thing turning a GuardDuty/Security Hub finding into
# a paged alert; a broken pattern (raised severity floor, dropped label, wrong source)
# silently swallows the exact high/critical findings that must never be missed.
run "eventbridge_patterns_match_high_severity" {
  command = plan

  # GuardDuty router: source aws.guardduty, GuardDuty Finding, severity >= 7.
  assert {
    condition = (
      jsondecode(aws_cloudwatch_event_rule.guardduty_high_severity[0].event_pattern).source == ["aws.guardduty"] &&
      jsondecode(aws_cloudwatch_event_rule.guardduty_high_severity[0].event_pattern)["detail-type"] == ["GuardDuty Finding"] &&
      jsondecode(aws_cloudwatch_event_rule.guardduty_high_severity[0].event_pattern).detail.severity[0].numeric[0] == ">=" &&
      jsondecode(aws_cloudwatch_event_rule.guardduty_high_severity[0].event_pattern).detail.severity[0].numeric[1] == 7
    )
    error_message = "GuardDuty rule must match source=aws.guardduty, GuardDuty Finding, severity numeric >= 7"
  }

  # Security Hub router: source aws.securityhub, Imported findings, CRITICAL & HIGH.
  assert {
    condition = (
      jsondecode(aws_cloudwatch_event_rule.securityhub_critical[0].event_pattern).source == ["aws.securityhub"] &&
      contains(jsondecode(aws_cloudwatch_event_rule.securityhub_critical[0].event_pattern).detail.findings.Severity.Label, "CRITICAL") &&
      contains(jsondecode(aws_cloudwatch_event_rule.securityhub_critical[0].event_pattern).detail.findings.Severity.Label, "HIGH")
    )
    error_message = "Security Hub rule must match source=aws.securityhub and escalate both CRITICAL and HIGH findings"
  }
}
